global using DynamicTabBar.Helpers;
global using DynamicTabBar.Models;
global using DynamicTabBar.ViewModels;
global using DynamicTabBar.Views.Pages;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
